---
- name: trace lldp
  gather_facts: false
  hosts: 
    - PRHMMN005-PE-03
    - PRHMMN006-SW-01
  vars:
    ansible_connection: network_cli
  tasks:
    - name: get facts from device
      napalm_get_facts:
        dev_os: "ios"
        filter: 
          - facts
          - lldp_neighbors
      register: result
    
    - name: print data
      debug: var=result

    - name: Generate graph description file
      template: src={{template|default('graph.j2')}} dest=./{{output|default('network.dot')}}
      run_once: true
